version: "3.8"

services:
  db:
    image: postgres
    container_name: wepresto_db
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: wepresto_db